GIT_URL = 'https://git.bbaovanc.com/bbaovanc/searx'
GIT_BRANCH = 'master'
ISSUE_URL = 'https://git.bbaovanc.com/bbaovanc/searx/issues'
SEARX_URL = 'https://searx.me'
DOCS_URL = 'https://searx.github.io/searx'
PUBLIC_INSTANCES = 'https://searx.space'
CONTACT_URL = 'mailto:searx-contact@bbaovanc.com'
